name: 'old-fourmolu-action'
description: 'Check formatting of Haskell code with Fourmolu.  This has been deprecated in favor of https://github.com/fourmolu/fourmolu-action'
inputs:
  pattern:
    required: false
    description: >
      Glob pattern that are used to find source files to format. It is
      possible to specify several patterns by putting each on a new line.
    default: |
      **/*.hs
      **/*.hs-boot
  follow-symbolic-links:
    required: false
    description: >
      Whether to follow symbolic links.
    default: true
  extra-args:
    required: false
    description: >
      Extra arguments to pass to Fourmolu.
runs:
  using: 'node12'
  main: 'dist/index.js'
